name: CI

on: 
  workflow_dispatch:
    inputs:
        authorship_analysis:
          description: "Enable authorship analysis?"
          type: boolean
          required: true
          default: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Dump debug_mode
      run: echo "Is authorship analysis enabled? ${{ inputs.authorship_analysis }}"
      shell: bash
    
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: pip install requests

    - name: Collect Workflow Telemetry
      uses: runforesight/workflow-telemetry-action@v1
    
    - name: Generate report (Main)
      if: ${{ !inputs.authorship_analysis }}
      run: bash ./run.sh
    
    - name: Generate report
      if: ${{ inputs.authorship_analysis }}
      run: bash ./run_authorship_analysis.sh
