name: CI
run-name: ${{ inputs.workflow_description }}

on: 
  workflow_dispatch:
    inputs:
        authorship_analysis:
          description: "Enable authorship analysis?"
          type: boolean
          required: true
          default: true
        workflow_description:
          description: "Workflow's Description"
          type: string
          required: true
        similarity_threshold:
          description: "Similarity Threshold"
          type: number
          required: true
          default: '0.8'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Dump debug_mode
      run: echo "Is authorship analysis enabled? ${{ inputs.authorship_analysis }}"
      shell: bash
    
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: pip install requests
    
    - name: Generate report (Artifact)
      run: bash ./run.sh ${{ inputs.authorship_analysis }} ${{ inputs.similarity_threshold }}
    
    - name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: reposense-report-${{ inputs.workflow_description }}
        path: /home/runner/work/tp-dashboard/tp-dashboard/reposense-report
